name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - numpy
  - anywidget>=0.9.0
  - ipywidgets
  - psygnal
  - sympy
  - pip:
      - kingdon