name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - numpy
  - ipywidgets
  - watchfiles
  - comm
  - anywidget
  - psygnal
  - sympy
  - pip:
      - kingdon
