# Useful Info

- title: README
  source: README.md
  icon: images/kingdon.svg
  type: markdown
  catalog: Other

- title: 2DPGA Cheat Sheet
  source: https://bivector.net/2DPGA.pdf
  type: url
  catalog: Other
  args:
    createNewWindow: true

- title: 3DPGA Cheat Sheet
  source: https://bivector.net/3DPGA.pdf
  type: url
  catalog: Other
  args:
    createNewWindow: true


# 2DPGA

- title: Distances and Angles
  source: content/2DPGA/ex_2dpga_distances_and_angles.ipynb
  icon: images/pga2d_distances_and_angles.svg
  type: notebook
  catalog: 2DPGA

- title: Points and Lines
  source: content/2DPGA/ex_2dpga_points_and_lines.ipynb
  icon: images/pga2d_points_and_lines.svg
  type: notebook
  catalog: 2DPGA

- title: Project and Reject
  source: content/2DPGA/ex_2dpga_project_and_reject.ipynb
  icon: images/pga2d_project_and_reject.svg
  type: notebook
  catalog: 2DPGA

- title: Inverse Kinematics
  source: content/2DPGA/ex_2dpga_inverse_kinematics.ipynb
  icon: images/pga2d_inverse_kinematics.svg
  type: notebook
  catalog: 2DPGA

- title: Fivebar
  source: content/2DPGA/ex_2dpga_fivebar.ipynb
  icon: images/pga2d_fivebar.svg
  type: notebook
  catalog: 2DPGA

- title: Tesseract on a string
  source: content/2DPGA/ex_2dpga_hypercube_on_string.ipynb
  icon: images/pga2d_hypercube_on_string.svg
  type: notebook
  catalog: 2DPGA

- title: Pointcloud Fitting
  source: content/ex_pointcloud.ipynb
  type: notebook
  catalog: 2DPGA

- title: Boids Algorithm
  source: content/ex_2dpga_boids.ipynb
  type: notebook
  catalog: 2DPGA

# 3DPGA

- title: Distances and Angles 3D
  source: content/3DPGA/ex_3dpga_distances_and_angles.ipynb
  icon: images/pga3d_distances_and_angles.svg
  type: notebook
  catalog: 3DPGA

- title: Points and Lines 3D
  source: content/3DPGA/ex_3dpga_points_and_lines.ipynb
  icon: images/pga3d_points_and_lines.svg
  type: notebook
  catalog: 3DPGA

- title: Thin Lens
  source: content/3DPGA/ex_3dpga_thinlens.ipynb
  type: notebook
  catalog: 3DPGA

- title: Beam on two strings
  source: content/3DPGA/ex_3dpga_beam_hooke_law.ipynb
  type: notebook
  catalog: 3DPGA

# 2DCGA

- title: Distances and Angles
  source: content/2DCGA/ex_2dcga_points_and_circles.ipynb
  icon: images/cga2d_points_and_circles.svg
  type: notebook
  catalog: 2DCGA

# 3DCGA

- title: Intersections
  source: content/3DCGA/ex_3dcga_intersections.ipynb
  type: notebook
  catalog: 3DCGA

- title: Parametric Surface
  source: content/3DCGA/ex_3dcga_parametric_surface.ipynb
  type: notebook
  catalog: 3DCGA

# Misc

- title: Symbolic Manipulation
  source: content/ex_symbolic.ipynb
  type: notebook
  catalog: Misc

# Exercises

- title: Spider 1
  source: content/exercises/spider1.ipynb
  icon: images/exercise_spider1.svg
  type: notebook
  catalog: Exercises

- title: Spider 2
  source: content/exercises/spider2.ipynb
  icon: images/exercise_spider2.svg
  type: notebook
  catalog: Exercises

- title: Spider 3
  source: content/exercises/spider3.ipynb
  icon: images/exercise_spider3.svg
  type: notebook
  catalog: Exercises

- title: Spider 4
  source: content/exercises/spider4.ipynb
  icon: images/exercise_spider4.svg
  type: notebook
  catalog: Exercises

- title: Spider 5
  source: content/exercises/spider5.ipynb
  icon: images/exercise_spider5.svg
  type: notebook
  catalog: Exercises

- title: Spider 6
  source: content/exercises/spider6.ipynb
  icon: images/exercise_spider6.svg
  type: notebook
  catalog: Exercises