# Useful Info

- title: README
  source: README.md
  icon: images/kingdon.svg
  type: markdown
  catalog: Other

# 2DPGA

- title: Distances and Angles
  source: content/2DPGA/ex_2dpga_distances_and_angles.ipynb
  icon: images/pga2d_distances_and_angles.svg
  type: notebook
  catalog: 2DPGA

- title: Points and Lines
  source: content/2DPGA/ex_2dpga_points_and_lines.ipynb
  icon: images/pga2d_points_and_lines.svg
  type: notebook
  catalog: 2DPGA

- title: Project and Reject
  source: content/2DPGA/ex_2dpga_project_and_reject.ipynb
  icon: images/pga2d_project_and_reject.svg
  type: notebook
  catalog: 2DPGA

- title: Inverse Kinematics
  source: content/2DPGA/ex_2dpga_inverse_kinematics.ipynb
  icon: images/pga2d_inverse_kinematics.svg
  type: notebook
  catalog: 2DPGA

- title: Fivebar
  source: content/2DPGA/ex_2dpga_fivebar.ipynb
  icon: images/pga2d_fivebar.svg
  type: notebook
  catalog: 2DPGA

- title: Pointcloud Fitting
  source: content/ex_pointcloud.ipynb
  type: notebook
  catalog: 2DPGA

# 3DPGA

- title: Distances and Angles 3D
  source: content/3DPGA/ex_3dpga_distances_and_angles.ipynb
  icon: images/pga3d_distances_and_angles.svg
  type: notebook
  catalog: 3DPGA

- title: Points and Lines 3D
  source: content/3DPGA/ex_3dpga_points_and_lines.ipynb
  icon: images/pga3d_points_and_lines.svg
  type: notebook
  catalog: 3DPGA

# 2DCGA

- title: Distances and Angles
  source: content/2DCGA/ex_2dcga_points_and_circles.ipynb
  icon: images/cga2d_points_and_circles.svg
  type: notebook
  catalog: 2DCGA

# 3DCGA

- title: Intersections
  source: content/3DCGA/ex_3dcga_intersections.ipynb
  type: notebook
  catalog: 3DCGA

# Misc

- title: Symbolic Manipulation
  source: content/ex_symbolic.ipynb
  type: notebook
  catalog: Misc
